export const buildingsData = [
  {
    id: "indochina-riverside-building",
    name: "Indochina Riverside Building",
    price: 22,
    serviceCharge: 5,
    district: "Hải Châu",
    address: "74 Bạch Đằng, Phường Hải Châu 1, Quận Hải Châu, Đà Nẵng",
    grade: "A",
    direction: "Đông",
    floorArea: "710m²",
    totalFloors: 12,
    availableAreas: "100m², 150m², 300m², 710m²",
    parkingFee: "Xe máy: 150.000đ/tháng, Ô tô: 2.000.000đ/tháng",
    electricityFee: "Theo chỉ số đồng hồ (3.800đ/kWh)",
    leaseTerm: "Tối thiểu 3 năm",
    deposit: "3 tháng",
    payment: "3 tháng/lần",
    image: "/assets/indochina_riverside.jpg",
    description: "Indochina Riverside Building là một trong những tòa nhà văn phòng Hạng A tiên phong tại Đà Nẵng. Sở hữu vị trí đắc địa ngay mặt tiền đường Bạch Đằng, hướng view trực diện sông Hàn thơ mộng. Tòa nhà được trang bị hệ thống điều hòa trung tâm hiện đại, 4 thang máy tốc độ cao, hệ thống kính cường lực cách âm cách nhiệt tốt, mang lại môi trường làm việc đẳng cấp cho các tập đoàn đa quốc gia và doanh nghiệp lớn.",
    amenities: ["View sông Hàn", "Thang máy tốc độ cao", "Lễ tân chuyên nghiệp", "Hệ thống PCCC tự động", "Bảo vệ 24/7", "Máy phát điện dự phòng 100%"]
  },
  {
    id: "bach-dang-complex",
    name: "Bạch Đằng Complex",
    price: 19,
    serviceCharge: 4,
    district: "Hải Châu",
    address: "50 Bạch Đằng, Phường Hải Châu 1, Quận Hải Châu, Đà Nẵng",
    grade: "A",
    direction: "Đông Nam",
    floorArea: "850m²",
    totalFloors: 29,
    availableAreas: "120m², 250m², 500m², 850m²",
    parkingFee: "Xe máy: 120.000đ/tháng, Ô tô: 1.800.000đ/tháng",
    electricityFee: "Theo thực tế tiêu thụ (3.500đ/kWh)",
    leaseTerm: "Tối thiểu 2 năm",
    deposit: "3 tháng",
    payment: "3 tháng/lần",
    image: "/assets/bach_dang_complex.jpg",
    description: "Nằm trong khu phức hợp khách sạn 5 sao và văn phòng cao cấp Hilton Da Nang, Bạch Đằng Complex là biểu tượng kiến trúc bên bờ sông Hàn. Tòa nhà mang thiết kế tân cổ điển sang trọng, tiện ích đẳng cấp quốc tế, đáp ứng đầy đủ tiêu chuẩn khắt khe nhất của văn phòng hạng A.",
    amenities: ["View sông Hàn", "Hầm giữ xe rộng rãi", "Tiện ích Hilton 5 sao", "Hội trường hội nghị", "An ninh đa lớp", "Hệ thống làm mát hiện đại"]
  },
  {
    id: "g8-golden-building",
    name: "G8 Golden Building",
    price: 13,
    serviceCharge: 3,
    district: "Hải Châu",
    address: "65 Hải Phòng, Phường Thạch Thang, Quận Hải Châu, Đà Nẵng",
    grade: "B",
    direction: "Bắc",
    floorArea: "350m²",
    totalFloors: 23,
    availableAreas: "80m², 150m², 200m², 350m²",
    parkingFee: "Xe máy: 100.000đ/tháng, Ô tô: 1.500.000đ/tháng",
    electricityFee: "Theo giá điện lực",
    leaseTerm: "Tối thiểu 2 năm",
    deposit: "3 tháng",
    payment: "3 tháng/lần",
    image: "/assets/g8_golden.jpg",
    description: "G8 Golden Building tọa lạc tại tuyến đường sầm uất Hải Phòng, trung tâm quận Hải Châu. Với thiết kế 23 tầng nổi hiện đại, mặt ngoài ốp kính xanh chống tia cực tím sang trọng, đây là địa chỉ thuê văn phòng Hạng B lý tưởng của nhiều startup công nghệ và doanh nghiệp tài chính.",
    amenities: ["Mặt kính xanh cách nhiệt", "Thang máy tốc độ cao", "Gần ga Đà Nẵng", "Lễ tân tầng trệt", "Vệ sinh hàng ngày"]
  },
  {
    id: "summit-building",
    name: "Summit Building",
    price: 15,
    serviceCharge: 3.5,
    district: "Thanh Khê",
    address: "350 Nguyễn Văn Linh, Phường Thạc Gián, Quận Thanh Khê, Đà Nẵng",
    grade: "B",
    direction: "Nam",
    floorArea: "420m²",
    totalFloors: 15,
    availableAreas: "100m², 210m², 420m²",
    parkingFee: "Xe máy: 100.000đ/tháng, Ô tô: 1.500.000đ/tháng",
    electricityFee: "Thực tế đồng hồ",
    leaseTerm: "Tối thiểu 2 năm",
    deposit: "3 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Tọa lạc trên trục đường tài chính - thương mại xương sống Nguyễn Văn Linh, Summit Building mang phong cách kiến trúc châu Âu hiện đại. Tòa nhà có vị trí đắc địa gần sân bay quốc tế Đà Nẵng, thích hợp làm trụ sở đại diện cho các doanh nghiệp logistics và công nghệ.",
    amenities: ["Gần sân bay", "Mặt tiền đường lớn", "Hầm xe rộng", "Lobby sang trọng", "Hệ thống điện dự phòng"]
  },
  {
    id: "thanh-loi-building-2",
    name: "Tòa nhà Thành Lợi 2",
    price: 14,
    serviceCharge: 3,
    district: "Thanh Khê",
    address: "1 Lê Đình Lý, Phường Vĩnh Trung, Quận Thanh Khê, Đà Nẵng",
    grade: "B",
    direction: "Tây Nam",
    floorArea: "500m²",
    totalFloors: 18,
    availableAreas: "120m², 200m², 350m²",
    parkingFee: "Xe máy: 100.000đ/tháng, Ô tô: 1.200.000đ/tháng",
    electricityFee: "3.700đ/kWh",
    leaseTerm: "Tối thiểu 2 năm",
    deposit: "3 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Thành Lợi 2 Building là tòa nhà văn phòng cao cấp nổi tiếng tại Thanh Khê. Thiết kế hiện đại, thông thoáng, tối ưu hóa ánh sáng tự nhiên. Đội ngũ quản lý chuyên nghiệp và nhiệt tình.",
    amenities: ["Sảnh đón tiếp rộng", "Hệ thống điều hòa âm trần", "Bảo vệ trực ban 24/7", "Quản lý tòa nhà chuyên nghiệp"]
  },
  {
    id: "mobifone-building",
    name: "Tòa nhà Mobifone Đà Nẵng",
    price: 12,
    serviceCharge: 2.5,
    district: "Cẩm Lệ",
    address: "Đường Nguyễn Hữu Thọ, Phường Khuê Trung, Quận Cẩm Lệ, Đà Nẵng",
    grade: "B",
    direction: "Đông Bắc",
    floorArea: "600m²",
    totalFloors: 9,
    availableAreas: "150m², 300m², 600m²",
    parkingFee: "Miễn phí xe máy số lượng hạn chế, Ô tô: 1.000.000đ/tháng",
    electricityFee: "Theo biểu giá nhà nước",
    leaseTerm: "Tối thiểu 2 năm",
    deposit: "3 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Tòa nhà Mobifone trên trục Nguyễn Hữu Thọ có khoảng sân đỗ xe cực rộng và không gian thoáng đãng. Là lựa chọn tuyệt vời cho các doanh nghiệp cần diện tích mặt sàn lớn với mức chi phí hợp lý.",
    amenities: ["Khoảng sân đỗ xe lớn", "Mặt bằng vuông vắn", "Môi trường yên tĩnh", "Bảo trì định kỳ miễn phí"]
  },
  {
    id: "wink-hotel-office",
    name: "Wink Hotel Trần Hưng Đạo",
    price: 25,
    serviceCharge: 5,
    district: "Sơn Trà",
    address: "351 Trần Hưng Đạo, Phường An Hải Tây, Quận Sơn Trà, Đà Nẵng",
    grade: "A",
    direction: "Tây",
    floorArea: "300m²",
    totalFloors: 24,
    availableAreas: "50m², 100m², 200m²",
    parkingFee: "Xe máy: 150.000đ/tháng, Ô tô: 2.200.000đ/tháng",
    electricityFee: "Đã bao gồm một phần trong phí quản lý",
    leaseTerm: "Tối thiểu 1 năm",
    deposit: "2 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Nằm trong khu phức hợp Wink Hotel sang trọng bậc nhất ven sông Hàn, khu văn phòng chia sẻ và văn phòng truyền thống tại Wink mang thiết kế cực kỳ trẻ trung, nhiều màu sắc năng động, phù hợp với thế hệ Millennials và Gen Z.",
    amenities: ["View sông Hàn trực diện", "Không gian co-working tiện nghi", "Khu ăn uống ẩm thực", "Phòng họp thông minh", "Quầy bar tầng thượng"]
  },
  {
    id: "luxury-building-tran-phu",
    name: "Luxury Building Trần Phú",
    price: 16,
    serviceCharge: 3.5,
    district: "Hải Châu",
    address: "205 Trần Phú, Phường Phước Ninh, Quận Hải Châu, Đà Nẵng",
    grade: "B",
    direction: "Đông",
    floorArea: "400m²",
    totalFloors: 11,
    availableAreas: "100m², 200m²",
    parkingFee: "Xe máy: 120.000đ/tháng, Ô tô: 1.600.000đ/tháng",
    electricityFee: "Tính theo công tơ riêng",
    leaseTerm: "Tối thiểu 2 năm",
    deposit: "3 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Luxury Building trên đường Trần Phú sở hữu thiết kế kính hộp hiện đại cách âm, giảm tiếng ồn đô thị tối đa. Không gian làm việc chuyên nghiệp, ấm cúng và đầy đủ tiện nghi.",
    amenities: ["Vị trí trung tâm hành chính", "Sảnh tiếp khách sang trọng", "Hệ thống chiếu sáng LED tiết kiệm điện", "Hai mặt tiền thoáng"]
  },
  {
    id: "ricco-building",
    name: "Ricco Building",
    price: 11,
    serviceCharge: 2,
    district: "Cẩm Lệ",
    address: "363 Nguyễn Hữu Thọ, Phường Khuê Trung, Quận Cẩm Lệ, Đà Nẵng",
    grade: "C",
    direction: "Đông",
    floorArea: "280m²",
    totalFloors: 8,
    availableAreas: "90m², 140m², 280m²",
    parkingFee: "Xe máy: 80.000đ/tháng, Ô tô: 1.000.000đ/tháng",
    electricityFee: "3.500đ/kWh",
    leaseTerm: "Tối thiểu 1 năm",
    deposit: "2 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Tòa nhà Ricco Cẩm Lệ cung cấp các mặt sàn văn phòng giá rẻ phù hợp túi tiền doanh nghiệp vừa và nhỏ tại Đà Nẵng. Thiết kế tối giản, sạch sẽ và an ninh đảm bảo tốt.",
    amenities: ["Giá thuê cực cạnh tranh", "Vệ sinh khu công cộng", "Bảo vệ trực giờ hành chính", "Có bãi đỗ xe phía trước"]
  },
  {
    id: "vietinbank-building",
    name: "Vietinbank Building Da Nang",
    price: 18,
    serviceCharge: 4,
    district: "Hải Châu",
    address: "36 Trần Quốc Toản, Phường Hải Châu 1, Quận Hải Châu, Đà Nẵng",
    grade: "B",
    direction: "Tây Nam",
    floorArea: "650m²",
    totalFloors: 27,
    availableAreas: "150m², 300m², 650m²",
    parkingFee: "Xe máy: 120.000đ/tháng, Ô tô: 1.700.000đ/tháng",
    electricityFee: "3.800đ/kWh",
    leaseTerm: "Tối thiểu 2 năm",
    deposit: "3 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Tòa nhà Vietinbank Đà Nẵng có chiều cao nổi bật tại trung tâm thành phố. Hệ thống trang thiết bị đạt chuẩn chất lượng cao, sảnh chờ chuyên nghiệp và tầm nhìn bao quát toàn bộ thành phố.",
    amenities: ["View toàn cảnh thành phố", "Thang máy Otis tốc độ cao", "Hệ thống quản lý BMS thông minh", "Trạm biến áp riêng biệt"]
  },
  {
    id: "viettronimex-building",
    name: "Viettronimex Building",
    price: 10,
    serviceCharge: 2,
    district: "Cẩm Lệ",
    address: "460 Nguyễn Hữu Thọ, Phường Khuê Trung, Quận Cẩm Lệ, Đà Nẵng",
    grade: "C",
    direction: "Đông Nam",
    floorArea: "320m²",
    totalFloors: 7,
    availableAreas: "80m², 160m²",
    parkingFee: "Xe máy: 70.000đ/tháng, Ô tô: 800.000đ/tháng",
    electricityFee: "Theo đơn giá nhà nước",
    leaseTerm: "Tối thiểu 1 năm",
    deposit: "2 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Viettronimex Building là giải pháp văn phòng tiết kiệm ngân sách hàng đầu khu vực Cẩm Lệ. Tòa nhà có sảnh đỗ xe rộng rãi, vị trí mặt tiền đường chính giao thương thuận lợi.",
    amenities: ["Bãi đỗ xe rộng rãi", "Chi phí vận hành thấp", "Có thang máy đi riêng", "Internet tốc độ cao sẵn có"]
  },
  {
    id: "camelia-building",
    name: "Camelia Building",
    price: 11,
    serviceCharge: 2,
    district: "Sơn Trà",
    address: "77 Ngô Quyền, Phường Mân Thái, Quận Sơn Trà, Đà Nẵng",
    grade: "C",
    direction: "Tây Bắc",
    floorArea: "250m²",
    totalFloors: 6,
    availableAreas: "70m², 120m², 250m²",
    parkingFee: "Xe máy: 80.000đ/tháng, Ô tô: Đỗ tự do ven đường",
    electricityFee: "3.600đ/kWh",
    leaseTerm: "Tối thiểu 1 năm",
    deposit: "2 tháng",
    payment: "3 tháng/lần",
    image: "/assets/modern_office_generic.jpg",
    description: "Camelia Building nằm trên đường Ngô Quyền kết nối giao thương thuận tiện đến cảng Tiên Sa và trung tâm thành phố. Thích hợp cho các văn phòng đại lý, hải quan, du lịch.",
    amenities: ["Mặt tiền thoáng rộng", "Camera an ninh 24/7", "Có thang máy vận chuyển", "Thiết bị chiếu sáng đầy đủ"]
  }
];
